[tool.poetry]
name = "cvss4py"
version = "0.1.0"
description = ""
authors = ["Ben Edwards <ben@cyentia.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
